phone: "022 328 369"
email: hor.svetivladikanikolaj.np@gmail.com
address: "Цара Душана 12, Нова Пазова"
instagram_url: "https://www.instagram.com/hornovapazova"
facebook_url: "https://www.facebook.com/HorNovaPazova"
youtube_url: "https://www.youtube.com/channel/UCHeA3i_Rdq_KfHwoMIjTJKg"
next_event_override: ""
